### ISSUE TITLE
Doc generation fails due to large files

### ISSUE THREAD

**Issue by tobiasgrosser** [opencompl/ssa#117]
/usr/bin/git push --force ***github.com/opencompl/ssa.git github-pages-deploy-action/8chs77ndm:gh-pages
remote: error: Trace: 022f1d5152edb2329e66f3e31eb99125f1cedbebe44eb8408f9784821131479a        
remote: error: See https://gh.io/lfs for more information.        
remote: error: File declarations/header-data.bmp is 116.10 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com./        
To https://github.com/opencompl/ssa.git
 ! [remote rejected] github-pages-deploy-action/8chs77ndm -> gh-pages (pre-receive hook declined)

Can we fix this or maybe just disable doc generation for now?

**Comment by bollu** [comment]
Fixed by moving to `mathlib` style deployment via Artifact + upload job. This required the changes from https://github.com/opencompl/ssa/commit/2368f09e7fe517ad5dbdac455a8f9dd429c20c23 and the commits behind it, along with changing the deployment settings in `Settings -> Pages` to "Github Actions"
