### ISSUE TITLE
`SSA.Projects.InstCombine.Test` is broken

### ISSUE THREAD

**Issue by alexkeizer** [opencompl/ssa#236]
I just noticed that if you open `SSA.Projects.InstCombine.Test` on main, it does not build.
It seems this file is outside the build hierarchy: `lake build`, and consequently CI, are still fine.

**Comment by bollu** [comment]
@alexkeizer do we need the file, or is it safe to drop?

**Comment by alexkeizer** [comment]
Well, it's a test, so we don't *need* it, but I'd like to understand what it was testing in the first place

**Comment by tobiasgrosser** [comment]
I fixed this  in 7c874634c08a7d7ca257f856275c73b70ed6e70c.
