### ISSUE TITLE
port alive mul/div operations into Lean

### ISSUE THREAD

**Issue by bollu** [opencompl/ssa#30]

**Comment by goens** [comment]
@bollu can you explain what you mean by this? are the definitions in [ForMathlib.lean:297-329](https://github.com/bollu/ssa/blob/e0bd7d86dd4f04a831a26c4465176ed5ae031760/SSA/Projects/InstCombine/ForMathlib.lean#L297-L329) incorrect?

**Comment by bollu** [comment]
@goens Let me elaborate. I produced the file [InstCombineAlive.lean](https://github.com/bollu/ssa/blob/main/SSA/Projects/InstCombine/InstCombineAlive.lean) by running the python script [`bollu/alive/1-tolean.py`](https://github.com/bollu/alive/blob/8ac3419f16cd91d93ede39543c7800c060383a05/1-tolean.py). This python script has support for all operations that occur in the `tests/instcombine/addsub.opt` test, and limited support for operations in the other files such as `tests/instcombine/muldivrem.opt`. The python script needs to be extended to add support for emitting the correct mapping from the Alive IR into our Lean encoding.

**Comment by bollu** [comment]
Any chance I can convince you extend the script to produce the other operations? :D I would like to believe that the code is written such that others can develop on it!

- The entrypoint is [`to_lean_prog` in `language.py`](https://github.com/bollu/alive/blob/main/language.py#L1368-L1405).
- New binary operations are to be added at [`to_lean_binop` in `language.py`](https://github.com/bollu/alive/blob/main/language.py#L1324)
- New unary and binary constants are to be added at [`to_lean_{unary, binary}_cst_value`](https://github.com/bollu/alive/blob/main/language.py#L1272-L1292)
-

**Comment by bollu** [comment]
https://github.com/bollu/alive/pull/1

**Comment by bollu** [comment]
Closed by https://github.com/opencompl/alive/pull/1
